Create new ecs-image module.
alibabacloud-automation/terraform-alicloud-ecs-image pull request #1
Opened 2020-02-18 14:59 UTC by zql-tqy

2020-02-19 02:02 UTC, Rich-yi commented on README.md
> +      disk_type = "data"
这个是格式化后的吗？

2020-02-19 02:02 UTC, Rich-yi commented on examples/image-create/main.tf
> +}
我看你这个example里面的module路径都一样，你问一下萧竹是不是应该写到一个module里面

2020-02-19 07:59 UTC, xiaozhu36 requested changes

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_image" "instance" {
resource "alicloud_image" "with_instance"

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_image" "snapshot" {
resource "alicloud_image" "with_snapshot"

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_image" "disk" {
resource "alicloud_image" "with_disk"

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +    create = "TF-instance_id"
Created = "Terraform"
Source = "Instance:var.instance_id"

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +  }, var.tags)
Created = "Terraform"
Source = "Snapshot:var.snapshot_id"

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +    create = "TF-disk"
Created = "Terraform"
Source = "Disk"

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +  architecture      = var.image_create_architecture
镜像的name怎么没有？

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +  description       = var.description
description       = "An image comes from disk device mapping and created by Terraform."

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +  description       = var.description
description       = "An image comes from snapshot var.snapshot_id and created by Terraform."

2020-02-19 07:59 UTC, xiaozhu36 commented on main.tf
> +  description       = var.description
description       = "An image comes from instance var.instance_id and created by Terraform."

2020-02-19 07:59 UTC, xiaozhu36 commented on modules/image-share-permission/main.tf
> +  account_id = var.account_id
这个module要加一个开关，
account_id 应该要支持一个list，并且这个module应该在主module中暴露出去

2020-02-19 07:59 UTC, xiaozhu36 commented on modules/image-copy/main.tf
> +  source_region_id = var.source_region_id
加一个开关
另外，这个地方后面还在看看怎么支持copy到多个region

2020-02-19 12:42 UTC, xiaozhu36 requested changes

2020-02-19 12:42 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_image_share_permission" "this" {
这个地方为啥不用 子module

2020-02-19 12:42 UTC, xiaozhu36 commented on main.tf
> +    Source  = "Instance:${var.instance_id[count.index]}"
这个地方为啥要取count.index

2020-02-19 12:42 UTC, xiaozhu36 commented on variables.tf
> +variable "account_id" {
account_ids

2020-02-21 01:32 UTC, xiaozhu36 requested changes

2020-02-21 01:32 UTC, xiaozhu36 commented on modules/image-share-permission/variables.tf
> +variable "share_image_id" {
改成 image_id

2020-02-21 01:32 UTC, xiaozhu36 commented on modules/image-share-permission/main.tf
> +  configuration_source    = "terraform-alicloud-modules/image-share-permission"
子module的格式以后通用为 "terraform-alicloud-modules/<主>/<子>"，如 "terraform-alicloud-modules/ecs-image/image-share-permission"

2020-02-21 01:32 UTC, xiaozhu36 commented on outputs.tf
> +  description = "The id of account that sharing image."
this_share_image_permission_account_ids

2020-02-21 01:32 UTC, xiaozhu36 commented on variables.tf
> +variable "share_image_id" {
这个应该不用吧，直接用创建好的imageid
这个module的工作就是创建module，然后可将其导出和分享

2020-02-21 01:32 UTC, xiaozhu36 commented on variables.tf
> +variable "image_id" {
这个也是

2020-02-21 01:34 UTC, xiaozhu36 requested changes

2020-02-21 01:34 UTC, xiaozhu36 commented on README-CN.md
> +  account_id     = ["59101469315*****"]
account_ids

2020-02-21 08:40 UTC, xiaozhu36 approved these changes

2020-02-21 08:40 UTC, merged